# Generated by Django 4.0.4 on 2022-08-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
