# Generated by Django 4.0.4 on 2022-08-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_level'),
        ('myapp', '0006_rename_student_id_profile_student'),
    ]

    operations = [
    ]
